### ISSUE TITLE
not able to start the local host

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex-website#1]
![image](https://user-images.githubusercontent.com/17708702/28919471-2531829c-783d-11e7-831b-04e27ce4a08a.png)

I have started backend and mongo server after following all the instructions provided.

**Comment by vinaypuppal** [comment]
Which node version do you have?
This app needs node version 8 or above

**Comment by M-ZubairAhmed** [comment]
yes using node 8 solved the issue.
